spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wavup
        username: huntley
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                globally_quoted_identifiers: true
            database: postgresql
            database-platform: org.hibernate.dialect.postgreSQLDialect
